version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: latest
    commands:
      - echo 'Install .NET 6'
      - wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - rm packages-microsoft-prod.deb
      - sudo apt-get update
      - sudo apt-get install -y apt-transport-https
      - sudo apt-get update
      - sudo apt-get install -y aspnetcore-runtime-6.0
      - dotnet --list-sdks
  pre_build:
    commands:
      - echo '------Pre Build Phase------'
      - echo '------Move to src Folder------'
      - cd src/
      - echo '------Restore Serendipity.WebApi.csproj------'
      - dotnet restore Serendipity.WebApi/Serendipity.WebApi.csproj
  build:
    commands:
      - echo '------Build Phase------'
      - echo '------Build Project------'
      - dotnet build Serendipity.WebApi/Serendipity.WebApi.csproj
  post_build:
    commands:
      - echo '------Post-Build Phase------'
      - echo '------Publish Project------'
      - dotnet publish -c Release -r linux-x64 -o ./build Serendipity.WebApi/Serendipity.WebApi.csproj