version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.it
      - PGADMIN_DEFAULT_PASSWORD=password